#
# Paths to various resources
#
set(ARDUINO_DEVROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
set(ARDUINO_LIBS ${ARDUINO_DEVROOT}/Libs)
set(ARDUINO_CMAKE_DIR ${ARDUINO_DEVROOT}/Config/CMake)
set(ARDUINO_TOOLCHAIN_DIR ${ARDUINO_DEVROOT}/Toolchain)
