set(ARDUINO_CORE_SRC ${ARDUINO_DEVROOT}/ArduinoCore-sam)
set(ARDUINO_MAIN_SOURCE ${ARDUINO_CORE_SRC}/cores/arduino/main.cpp)
if(NOT DEFINED ARDUINO_BUILD_FOR_HOST)
  set(ARDUINO_HANDLER_SOURCE ${ARDUINO_CORE_SRC}/cores/arduino/cortex_handlers.c)
endif()
