if ("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
elseif ("${CMAKE_BUILD_TYPE}" STREQUAL "RelWithDebInfo")
elseif ("${CMAKE_BUILD_TYPE}" STREQUAL "MinSizeRel")
else ()
    set(CMAKE_BUILD_TYPE Debug)
endif ()


if ("${ARDUINO_LIBS_BUILD}" STREQUAL "")
    set(ARDUINO_LIBS_BUILD ${CMAKE_BUILD_TYPE})
endif ()

set(ARDUINO_LIB_SUBDIR "out.${ARDUINO_PLATFORM}-${ARDUINO_LIBS_BUILD}")
set(PROJECT_OUTPUT_DIR ${CMAKE_BINARY_DIR}/out.${ARDUINO_PLATFORM}-${CMAKE_BUILD_TYPE})

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_OUTPUT_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_OUTPUT_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_OUTPUT_DIR})

