add_compile_options(-Wall -c -fmessage-length=0)
add_compile_options(-ffunction-sections -fdata-sections -fno-common)
add_link_options(-Wl,-gc-sections)
add_link_options(-Wl,--check-sections -Wl,--unresolved-symbols=report-all -Wl,--warn-common -Wl,--warn-section-align)

set(ARDUINO_OPTIMIZATIONS debug)
if ("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
    message(STATUS "Target type = Release")
    set(ARDUINO_OPTIMIZATIONS speed)
elseif ("${CMAKE_BUILD_TYPE}" STREQUAL "RelWithDebInfo")
    message(STATUS "Target type = RelWithDebInfo")
    set(ARDUINO_OPTIMIZATIONS speedDbg)
elseif ("${CMAKE_BUILD_TYPE}" STREQUAL "MinSizeRel")
    message(STATUS "Target type = MinSizeRel")
    set(ARDUINO_OPTIMIZATIONS size)
else ()
    message(STATUS "Target type = Debug")
endif ()

if ("${ARDUINO_OPTIMIZATIONS}" STREQUAL "speed")
    message(STATUS "Maximum optimization for speed")
    add_compile_options(-Ofast)
elseif ("${ARDUINO_OPTIMIZATIONS}" STREQUAL "speedDbg")
    message(STATUS "Maximum optimization for speed, debug info included")
    add_compile_options(-Ofast -g)
elseif ("${ARDUINO_OPTIMIZATIONS}" STREQUAL "size")
    message(STATUS "Maximum optimization for size")
    add_compile_options(-Os)
    add_link_options(-Os)
else ()
    message(STATUS "Minimal optimization, debug info included")
    add_compile_options(-Og -g3)
endif ()

