add_compile_options(-Wall -c -fmessage-length=0)
add_compile_options(-ffunction-sections -fdata-sections -fno-common)
add_link_options(-Wl,-gc-sections)
add_link_options(-Wl,--check-sections -Wl,--unresolved-symbols=report-all -Wl,--warn-common -Wl,--warn-section-align)

if ("${CMAKE_BUILD_TYPE}" STREQUAL "Release")
    message(STATUS "Maximum optimization for speed")
    add_compile_options(-Ofast)
elseif ("${CMAKE_BUILD_TYPE}" STREQUAL "RelWithDebInfo")
    message(STATUS "Maximum optimization for speed, debug info included")
    add_compile_options(-Ofast -g)
elseif ("${CMAKE_BUILD_TYPE}" STREQUAL "MinSizeRel")
    message(STATUS "Maximum optimization for size")
    add_compile_options(-Os)
    add_link_options(-Os)
else ()
    set(CMAKE_BUILD_TYPE Debug)
    message(STATUS "Minimal optimization, debug info included")
    add_compile_options(-Og -g3)
endif ()

if ("${ARDUINO_LIBS_BUILD}" STREQUAL "")
    set(ARDUINO_LIBS_BUILD ${CMAKE_BUILD_TYPE})
endif ()
